GET http://127.0.0.1:8000/items/
###
POST http://127.0.0.1:8000/items/
content-type: application/json

{
    "name": "British Musuem All Day",
    "description": "Three days",
    "price": 6500
}
###
PUT http://127.0.0.1:8000/items/1
content-type: application/json

{
    "name": "British Musuem All Day",
    "description": "Two days",
    "price": 4300.0,
    "tax": 315.00000000000006,
    "id": 1
}
###
DELETE http://127.0.0.1:8000/items/9
###
# Hello